In [1]:
# File location and type
file_location = "/FileStore/tables/climate_csv.csv"
file_type = "csv"

# CSV options
infer_schema = "false"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
df = spark.read.format(file_type) \
  .option("inferSchema", infer_schema) \
  .option("header", first_row_is_header) \
  .option("sep", delimiter) \
  .load(file_location)

In [2]:
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext
from pyspark.sql.functions import col, when, lit, concat, round, sum

In [3]:
df.count()

In [4]:
df.registerTempTable("climate")

In [6]:
%sql
SELECT  country_name, y2004, y2014 FROM climate B WHERE B.indicator_name='Renewable energy consumption (% of total final energy consumption)' and y2014<y2004  order by y2004 desc Limit 10

country_name,y2004,y2014
"Congo, Dem. Rep.",97.88,92.87
Burundi,97.27,94.6
Ethiopia,94.66,92.07
Uganda,93.92,90.22
Bhutan,93.45,87.03
Mozambique,92.92,88.86
Chad,92.12,89.24
Tanzania,91.73,86.67
Nepal,90.3,84.37
Liberia,90.18,83.94

In [7]:
%sql
SELECT  country_name, y2014 FROM climate B WHERE B.indicator_name='CO2 emissions (metric tons per capita)' order by y2014 desc Limit 10

country_name,y2014
Netherlands,9.92
Japan,9.54
OECD members,9.52
Norway,9.27
Libya,9.19
Cayman Islands,9.17
Czech Republic,9.17
Greenland,8.99
South Africa,8.98
Germany,8.89

In [8]:
%sql
SELECT  country_name, y2004, y2014, round(y2014-y2004,2) as difference FROM climate  WHERE indicator_name='CO2 emissions (metric tons per capita)' and y2014-y2004>0 order by difference desc Limit 10

country_name,y2004,y2014,difference
Curacao,0.0,37.73,37.73
Sint Maarten (Dutch part),0.0,19.46,19.46
Trinidad and Tobago,25.91,34.16,8.25
Brunei Darussalam,13.9,22.12,8.22
Serbia,0.0,5.28,5.28
New Caledonia,11.06,16.01,4.95
Oman,11.45,15.44,3.99
Mongolia,3.42,7.13,3.71
Montenegro,0.0,3.56,3.56
China,4.04,7.54,3.5

In [9]:
%sql
SELECT  country_name, y2000, y2014 FROM climate  WHERE indicator_name='Electricity production from nuclear sources (% of total)' order by y2014-y2004 desc Limit 10

country_name,y2000,y2014
Hungary,40.29,53.24
Finland,32.12,34.63
Romania,10.51,17.91
Czech Republic,18.64,35.64
"Iran, Islamic Rep.",0.0,1.63
Pakistan,2.93,4.76
Russian Federation,14.91,17.02
Slovenia,34.95,37.11
Slovak Republic,53.56,57.09
Canada,12.02,16.12

In [10]:
df1=spark.sql("select country_name, round(y2000+y2014,2) as new2014 from climate where indicator_name='Electricity production from nuclear sources (% of total)' order by new2014 desc").limit(10)

In [11]:
display(df1)

country_name,new2014
France,155.81
Slovak Republic,110.65
Belgium,105.32
Ukraine,93.73
Hungary,93.53
Sweden,81.72
Switzerland,79.3
Bulgaria,78.53
Lithuania,75.7
Slovenia,72.06

In [12]:
%sql
SELECT  country_name, y2000, y2014 FROM climate  WHERE indicator_name='Electricity production from nuclear sources (% of total)' order by y2014-y2004 desc Limit 10

country_name,y2000,y2014
Hungary,40.29,53.24
Finland,32.12,34.63
Romania,10.51,17.91
Czech Republic,18.64,35.64
"Iran, Islamic Rep.",0.0,1.63
Pakistan,2.93,4.76
Russian Federation,14.91,17.02
Slovenia,34.95,37.11
Slovak Republic,53.56,57.09
Canada,12.02,16.12